### PR TITLE
Replace cal.createAdapter-based calendar observers with explicit calIObserver objects

### LINKED ISSUE #66: calendar experiment breaks on Thunderbird 149: cal.createAdapter is not a function in ext-calendar-items.js
## Summary

The calendar experiment from this repository appears to break on Thunderbird Release 149 because `cal.createAdapter` is no longer available.

This prevents `calendar.items.*` listeners from being registered and breaks persisted calendar monitoring.

## Observed behavior

On Thunderbird 149, the following runtime errors appear when the experiment listeners are registered:

```text
cal.createAdapter is not a function ext-calendar-items.js:167:36
cal.createAdapter is not a function ext-calendar-items.js:184:36
cal.createAdapter is not a function ext-calendar-items.js:203:36
```
As a result, callbacks for these events no longer fire:

browser.calendar.items.onCreated
browser.calendar.items.onUpdated
browser.calendar.items.onRemoved

### PR DESCRIPTION
**Pull request by DeBaschdi**
Fixes #66

## Summary

This PR replaces `cal.createAdapter(Ci.calIObserver, ...)` usage in the calendar experiment with explicit `calIObserver` objects using:

```js
QueryInterface: ChromeUtils.generateQI(["calIObserver"])
```

## Problem

On newer Thunderbird releases, `cal.createAdapter` is no longer available.

That breaks listener registration in the calendar experiment and prevents these experiment events from being registered correctly:

- `calendar.items.onCreated`
- `calendar.items.onUpdated`
- `calendar.items.onRemoved`
- `calendar.calendars.onUpdated`

## Cause

The experiment currently relies on:

```js
cal.createAdapter(Ci.calIObserver, { ... })
```

for internal observer creation.

When that helper is unavailable, observer registration fails before `cal.manager.addCalendarObserver(observer)` can succeed.

## Fix

Replace the removed helper usage with explicit `calIObserver` objects.

The patch adds small local helpers which provide:

- `QueryInterface: ChromeUtils.generateQI(["calIObserver"])`
- no-op implementations for unused observer callbacks
- only the event-specific methods overridden where needed

This keeps the public experiment API unchanged and only updates internal observer construction.

## Affected files

- `calendar/experiments/calendar/parent/ext-calendar-items.js`
- `calendar/experiments/calendar/parent/ext-calendar-calendars.js`

## Verification

Verified manually on:

- Thunderbird ESR 140
- Thunderbird Release 149

After the patch:
- `calendar.items.onCreated` works
- `calendar.items.onUpdated` works
- `calendar.items.onRemoved` works
- `calendar.calendars.onUpdated` works
- the previous `cal.createAdapter is not a function` runtime errors are gone

## Notes

This is a compatibility fix only.
It does not change the public experiment API surface or semantics.

### CODE REVIEW

**Comment by kewisch** [comment]
@mkmelin can you give this a quick look? I believe you removed createAdapter in core code.

**Comment by DeBaschdi** [comment]
One more note on downstream impact:

NC Connector depends on the persisted "browser.calendar.items.*" lifecycle events provided by this experiment layer. These events are not just used for UI updates, but for the add-on's post-save synchronization flow after a calendar item is actually created, updated, or removed.

In practice, that flow is used to keep Talk room metadata in sync with the saved event, persist the event↔room mapping, run deferred participant/delegation updates, and clean up associated Talk rooms again when an event is deleted.

So while restoring an equivalent helper in core would of course also help downstream consumers, this PR keeps the fix local and minimal by removing the experiment's remaining dependency on "cal.createAdapter()".

File: calendar/experiments/calendar/parent/ext-calendar-items.js [hunk 1]
```diff
@@ -7,6 +7,29 @@ var { ExtensionUtils: { ExtensionError } } = ChromeUtils.importESModule("resourc
 
 var { cal } = ChromeUtils.importESModule("resource:///modules/calendar/calUtils.sys.mjs");
 
+/**
+ * Thunderbird 149 no longer exposes cal.createAdapter(). Build explicit
+ * calIObserver objects so the vendored calendar experiment keeps working on
+ * newer release channels as well as ESR.
+ *
+ * @param {object} methods
+ * @returns {object}
```
Comment (mkmelin) [inline calendar/experiments/calendar/parent/ext-calendar-items.js]: @returns {calIObserver}

**Review by mkmelin — COMMENTED** [review]
Seems ok to me, thanks!

File: calendar/experiments/calendar/parent/ext-calendar-items.js (hunk 1 above)
Comment (DeBaschdi) [reply calendar/experiments/calendar/parent/ext-calendar-items.js]: JSDoc types adjusted

**Comment by DeBaschdi** [comment]
createCalendarObserver() is added twice with the same implementation — should we move that into a shared helper?

**Comment by kewisch** [comment]
Yes I think you can put it in ext-calendar-utils.sys.mjs ?

**Review by kewisch — APPROVED** [review]
